# Generated by Django 2.2.4 on 2019-09-04 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.CharField(choices=[('CSE', 'COMPUTER SCIENCE AND ENGINEERING'), ('ECE', 'ELECTRONICS AND COMMUNICATION ENGINEERING'), ('ME', 'MECHANICAL ENGINEERING'), ('EE', 'ELECTRICAL ENGINEERING'), ('EI', 'ELECTRONICS & INSTRUMENTATION ENGINEERING'), ('CE', 'CIVIL ENGINEERING')], default=1, max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('active', models.CharField(choices=[('N', 'NO'), ('Y', 'YES')], default='Y', max_length=1)),
                ('employeeType', models.IntegerField(choices=[(1, 'FACULTY'), (2, 'ACCOUNT'), (3, 'DIRECTOR'), (4, 'PURCHASE'), (5, 'REGISTRAR')], default=1)),
                ('jobType', models.CharField(choices=[('FT', 'FULL TIME'), ('PT', 'PART TIME'), ('C', 'CONTRACTUAL'), ('V', 'VISITING')], default=1, max_length=2)),
                ('dateOfBirth', models.DateField()),
                ('address', models.TextField()),
                ('dateOfJoining', models.DateField()),
                ('contactNo', models.CharField(max_length=10)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.Department')),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.FloatField()),
                ('dateOfFundReceive', models.DateField()),
                ('financialYear', models.IntegerField(choices=[(2018, '2018-19'), (2019, '2019-20'), (2020, '2020-21'), (2021, '2021-22'), (2022, '2022-23'), (2023, '2023-24')], default=0)),
                ('fundDescription', models.TextField()),
                ('fundDistributed', models.CharField(choices=[('N', 'NO'), ('Y', 'YES')], default='N', max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dateofIndent', models.DateField(auto_now_add=True)),
                ('purpose', models.TextField()),
                ('specification', models.TextField()),
                ('totalCost', models.FloatField(default=0)),
                ('currentStatus', models.IntegerField(choices=[(0, 'Purchase Request Saved in Draft'), (1, 'Purchase Request is with HOD'), (2, 'Waiting for approval by HOD'), (3, 'Purchase Request is in Account Section'), (4, 'Waiting for Approval by Account Section'), (5, 'Waiting for Approval by Registrar'), (6, 'Waiting for Approval by Director'), (7, 'Approved by Account Section'), (8, 'Purchase Request at Purchase Section'), (9, 'Product Purchased'), (10, 'Purchase denied')], default=0)),
                ('moneyGranted', models.CharField(choices=[('N', 'NO'), ('Y', 'YES')], default='N', max_length=1)),
                ('log', models.TextField()),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.Department')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='HOD',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfAppointment', models.DateField()),
                ('lastDateOfService', models.DateField(blank=True, null=True)),
                ('currentlyServing', models.CharField(choices=[('N', 'NO'), ('Y', 'YES')], default='Y', max_length=1)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.Department')),
                ('hOD', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='FundDistribution',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('totalAmountReceived', models.FloatField(default=0.0)),
                ('fundUsed', models.FloatField(default=0.0)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.Department')),
                ('fund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.Fund')),
            ],
        ),
    ]
