# Generated by Django 2.2.4 on 2019-08-28 04:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoreFund',
            fields=[
                ('FundID', models.AutoField(primary_key=True, serialize=False)),
                ('FyStart', models.DateField()),
                ('Amount', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('DeptID', models.CharField(choices=[('CSE', 'COMPUTER SCIENCE AND ENGINEERING'), ('ECE', 'ELECTRONICS AND COMMUNICATION ENGINEERING'), ('ME', 'MECHANICAL ENGINEERING'), ('EE', 'ELECTRICAL ENGINEERING'), ('EI', 'ELECTRONICS & INSTRUMENTATION ENGINEERING'), ('CE', 'CIVIL ENGINEERING')], default=1, max_length=3, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('EmpID', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('FirstName', models.CharField(max_length=100)),
                ('LastName', models.CharField(max_length=100)),
                ('DOB', models.DateField()),
                ('Designation', models.IntegerField(choices=[(1, 'ASSISTANT PROFESSOR'), (2, 'ASSOCIATE PROFESSOR'), (3, 'PROFESSOR')], default=1)),
                ('Address', models.TextField()),
                ('DOJ', models.DateField()),
                ('ContactNo', models.CharField(max_length=10)),
                ('ActiveStatus', models.CharField(choices=[('N', 'NO'), ('Y', 'YES')], default=1, max_length=1)),
                ('EmpType', models.CharField(choices=[('FT', 'FULL TIME'), ('PT', 'PART TIME'), ('C', 'CONTRACTUAL'), ('V', 'VISITING')], default=1, max_length=1)),
                ('DeptID', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.Department')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseRequest',
            fields=[
                ('PurchaseID', models.AutoField(primary_key=True, serialize=False)),
                ('DateofIndent', models.DateField()),
                ('Purpose', models.TextField()),
                ('Specification', models.TextField()),
                ('RatePerUnit', models.FloatField()),
                ('NoOfItemsReq', models.IntegerField()),
                ('CurrentStatus', models.IntegerField(choices=[(0, 'Purchase Request Generated'), (1, 'Waiting for approval by HOD'), (2, 'Approved by HOD'), (3, 'Waiting for Approval by Account Section'), (4, 'Approved by Account Section'), (5, 'Purchase Request at Purchase Section'), (6, 'Product Purchased'), (7, 'Purchase denied')])),
                ('DeptID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.Department')),
                ('EmpID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.Employee')),
            ],
        ),
        migrations.CreateModel(
            name='FundDistribution',
            fields=[
                ('DistID', models.AutoField(primary_key=True, serialize=False)),
                ('TotalAmountReceived', models.FloatField()),
                ('FundUse', models.FloatField()),
                ('DeptID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.Department')),
                ('FundID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.CoreFund')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='HODID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utility.Employee'),
        ),
        migrations.CreateModel(
            name='AccountSection',
            fields=[
                ('AccountID', models.AutoField(primary_key=True, serialize=False)),
                ('MoneyGranted', models.CharField(choices=[('N', 'NO'), ('Y', 'YES')], max_length=1)),
                ('AccountOfficer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.Employee')),
                ('PurchaseID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utility.PurchaseRequest')),
            ],
        ),
    ]
