# Generated by Django 2.2.4 on 2019-09-09 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0003_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
