# Generated by Django 2.2.4 on 2019-10-02 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0007_purchasereqlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='description',
            field=models.TextField(default='description missing'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='employeeType',
            field=models.IntegerField(choices=[(1, 'FACULTY'), (2, 'ACCOUNT'), (3, 'REGISTRAR'), (4, 'DIRECTOR'), (5, 'PURCHASE')], default=1),
        ),
        migrations.AlterField(
            model_name='purchasereqlog',
            name='changedTo',
            field=models.IntegerField(choices=[(0, 'Waiting for approval by HOD'), (1, 'Waiting for Approval by Account Section'), (2, 'Waiting for Approval by Registrar'), (3, 'Waiting for Approval by Director'), (4, 'Purchase Request at Purchase Section'), (5, 'Product Purchased'), (6, 'Purchase denied')], default=1),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='currentStatus',
            field=models.IntegerField(choices=[(0, 'Waiting for approval by HOD'), (1, 'Waiting for Approval by Account Section'), (2, 'Waiting for Approval by Registrar'), (3, 'Waiting for Approval by Director'), (4, 'Purchase Request at Purchase Section'), (5, 'Product Purchased'), (6, 'Purchase denied')], default=0),
        ),
    ]
