# Generated by Django 2.2.4 on 2019-10-02 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0008_auto_20191002_1138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchaserequest',
            name='specification',
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='feasible',
            field=models.CharField(default='Yes', max_length=500),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='preferenceReason',
            field=models.CharField(default='No reason specified', max_length=500),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='proprietary',
            field=models.CharField(default='No', max_length=500),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='requirementPeriod',
            field=models.CharField(default='1 year', max_length=500),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='requirementProjection',
            field=models.CharField(default='No', max_length=500),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='requirementUrgency',
            field=models.CharField(default='Not Urgent', max_length=500),
        ),
        migrations.AddField(
            model_name='purchaserequest',
            name='scheme',
            field=models.CharField(default='No Scheme', max_length=500),
        ),
        migrations.AlterField(
            model_name='purchaserequest',
            name='purpose',
            field=models.CharField(default='No purpose specified', max_length=500),
        ),
    ]
