# Generated by Django 2.2.4 on 2019-10-02 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utility', '0009_auto_20191002_2108'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaserequest',
            name='specification',
            field=models.TextField(default='Not specified'),
            preserve_default=False,
        ),
    ]
